Fix wrong input key name (#1300)
ValueError: The metric [context_utilization] that that is used requires
the following additional columns ['retreived_contexts'] to be present in
the dataset.